# Generated by Django 4.2.2 on 2023-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=10000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10, verbose_name='Unique ID'),
        ),
    ]
